name: Run samples

on:
  push:
    branches:
    - develop
    - feature/*

jobs:
  run_samples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        define:
        - ''

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Install dependencies
      run: 'sudo apt update

        sudo apt install -y build-essential

        sudo apt install -y python3.12

        sudo apt install -y python3.12-dev

        sudo apt install -y python3.12-venv

        '
    - name: Set up Python environment
      run: 'python3.12 -m venv /opt/venv_py_samples

        /opt/venv_py_samples/bin/pip install --upgrade pip

        /opt/venv_py_samples/bin/pip install --upgrade setuptools

        /opt/venv_py_samples/bin/pip install numpy matplotlib scipy control sympy astor plotly dash

        '
    - name: Run samples
      env:
        MPLBACKEND: Agg
      run: '/opt/venv_py_samples/bin/python3 ./sample/kalman_filter/EKF_two_wheel_vehicle_model.py

        /opt/venv_py_samples/bin/python3 ./sample/kalman_filter/extended_kalman_filter.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/kalman_filter/extended_kalman_filter.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/kalman_filter/linear_kalman_filter.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/kalman_filter/linear_kalman_filter.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/kalman_filter/lkf_fixed_G.py

        /opt/venv_py_samples/bin/python3 ./sample/kalman_filter/unscented_kalman_filter.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/kalman_filter/unscented_kalman_filter.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/least_squares/least_squares_method.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/least_squares/least_squares_method.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/least_squares/recursive_squares_method.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/least_squares/recursive_squares_method.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/lqr/discrete_state_space_lqi_easy.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/lqr/discrete_state_space_lqi_easy.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/lqr/discrete_state_space_lqr.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/lqr/discrete_state_space_lqr.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/pid_controller/discrete_pid_controller.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/pid_controller/discrete_pid_controller.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/pid_controller/servo_motor_pid_control.py

        /opt/venv_py_samples/bin/python3 ./sample/state_space/discrete_state_space_1.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/state_space/discrete_state_space_1.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/state_space/discrete_state_space_2.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/state_space/discrete_state_space_2.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/transfer_function/discrete_transfer_function_2_4.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/transfer_function/discrete_transfer_function_2_4.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/transfer_function/discrete_transfer_function_3_4.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/transfer_function/discrete_transfer_function_3_4.cpp

        ./sample/app

        /opt/venv_py_samples/bin/python3 ./sample/transfer_function/discrete_transfer_function_4_4.py

        g++ -std=c++11 -Wall -Werror -I ./python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/transfer_function/discrete_transfer_function_4_4.cpp

        ./sample/app

        '
