name: Run test VS

on:
  push:
    branches: [ create_SIL ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        define:
          - ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential
        sudo apt install -y cmake
        sudo apt install -y pybind11-dev

# cmake pybind11-dev python3.12 python3.12-dev python3.12-venv

    # - name: Set up Python environment
    #   run: |
    #     python3 -m venv /opt/venv_py_MCAP
    #     /opt/venv_py_MCAP/bin/pip install --upgrade pip && /opt/venv_py_MCAP/bin/pip install --upgrade setuptools
    #     /opt/venv_py_MCAP/bin/pip install numpy control matplotlib mplcursors pandas jupyter openpyxl sympy astor pybind11 networkx
    #     apt install -y -q python3-tk

    # - name: Run SIL tests
    #   run: |
    #     /opt/venv_py_MCAP/bin/python3 ./test_sil/discrete_state_space/discrete_state_space_1_SIL.py
